version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./schema.yaml:/app/schema.yaml
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - SQLITE_DATABASE_URL=sqlite:///./adlbuilder.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
