version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./schema.yaml:/app/schema.yaml
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - SQLITE_DATABASE_URL=sqlite:///./adlbuilder.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
